/*
 * Block-level image operations for zero-knowledge proof generation.
 *
 * Functions for computing run-length block structure from BitMatrix images,
 * used to build lookup tables for the ZK proof system.
 */

use crate::common::BitMatrix;
use crate::witness_data::types::BlockLookup;

// Width-word lookup tables live in width_tables.rs (generated by python-scripts/codewords_array.py).
pub use super::width_tables::VALID_WIDTH_WORDS;
use super::width_tables::WIDTH_TO_CODEWORD;

/// Little-endian base-13 encoding of a 6-element width pattern.
/// Width values are pairwise sums of adjacent PDF417 bars/spaces (range 2–12).
/// Base 13 is the tightest safe base; max 6-element word ≈ 5.87M.
pub fn get_word(widths: &[u32; 6]) -> u64 {
    widths
        .iter()
        .enumerate()
        .map(|(i, &w)| w as u64 * 13u64.pow(i as u32))
        .sum()
}

/// Width-word (base-13) for the PDF417 start pattern [8,1,1,1,1,1,1,3] → widths [9,2,2,2,2,2]
pub const START_WORD: u64 = 804475;
/// Width-word (base-13) for the PDF417 stop pattern [7,1,1,3,1,1,1,2] → widths [8,2,4,4,2,2]
pub const STOP_WORD: u64 = 809206;

fn decodes_exactly(widths: &[u32; 6]) -> bool {
    let word = get_word(widths);
    word != 0
        && WIDTH_TO_CODEWORD
            .get(&word)
            .is_some_and(|&cw| cw != DUMMY_CW)
}

fn ext_codeword_of_width(word: u64) -> u32 {
    if word == 0 || word == START_WORD || word == STOP_WORD {
        return DUMMY_CW;
    }
    *WIDTH_TO_CODEWORD
        .get(&word)
        .unwrap_or_else(|| panic!("ext_codeword_of_width called on non-decodable word {word}"))
}

/// Computes raw words from normalized widths: each [u32; 6] → u64 via get_word.
pub fn compute_words(normalized_widths: &[Vec<[u32; 6]>]) -> Vec<Vec<u64>> {
    normalized_widths
        .iter()
        .map(|row| row.iter().map(|w| get_word(w)).collect())
        .collect()
}

/// Reconstructs the pre-EC codeword array from `words_with_dummies` and `ext_codewords`,
/// matching exactly what the circuit extracts into `cw_and_dummies`.
///
/// For each active row (not all-zero in words_with_dummies), collects ext_codeword values
/// at columns j >= 2 that decoded exactly (ext_cw != DUMMY_CW), excluding the right row
/// indicator (the column immediately before STOP) and all columns from STOP onward.
/// Result is left-padded with zeros to `max_codewords`.
pub fn codewords_from_words_and_ext(
    words_with_dummies: &[Vec<u64>],
    ext_codewords: &[Vec<u32>],
    max_codewords: usize,
) -> Vec<u32> {
    let mut result: Vec<u32> = Vec::new();
    for (row_words, row_ext) in words_with_dummies.iter().zip(ext_codewords.iter()) {
        if row_words.iter().all(|&w| w == 0) {
            continue;
        }
        let stop_pos = row_words.iter().position(|&w| w == STOP_WORD);
        for j in 2..row_words.len() {
            if let Some(sp) = stop_pos {
                if j >= sp {
                    break;
                }
                if j == sp - 1 {
                    continue; // right row indicator
                }
            }
            let ext_cw = row_ext[j];
            if ext_cw != DUMMY_CW {
                result.push(ext_cw);
            }
        }
    }
    let n = result.len().min(max_codewords);
    let mut padded = vec![0u32; max_codewords];
    padded[max_codewords - n..].copy_from_slice(&result[..n]);
    padded
}

/// [u32; 6] variant of compute_words_with_dummies.
/// Uses base-13 width-word encoding and table-based validity check.
pub fn compute_words_with_dummies(
    normalized_widths: &[Vec<[u32; 6]>],
) -> (Vec<Vec<u64>>, Vec<u64>) {
    let mut garbage = Vec::new();
    let all_words: Vec<Vec<u64>> = normalized_widths
        .iter()
        .map(|row| row.iter().map(|w| get_word(w)).collect())
        .collect();
    let words_with_dummies: Vec<Vec<u64>> = normalized_widths
        .iter()
        .enumerate()
        .map(|(i, row)| {
            let is_consecutive_duplicate = i > 0 && all_words[i] == all_words[i - 1];
            if is_consecutive_duplicate {
                vec![0u64; row.len()]
            } else {
                row.iter()
                    .enumerate()
                    .map(|(j, widths)| {
                        let word = get_word(widths);
                        if word == START_WORD || word == STOP_WORD || decodes_exactly(widths)
                        {
                            word
                        } else {
                            let same_as_prev = i > 0 && word == all_words[i - 1][j];
                            if !same_as_prev {
                                garbage.push(word);
                            }
                            0
                        }
                    })
                    .collect()
            }
        })
        .collect();
    let garbage_len = words_with_dummies.len() * words_with_dummies[0].len();
    garbage.resize(garbage_len, 1);
    (words_with_dummies, garbage)
}

/// [u32; 6] variant of compute_ext_codewords. Uses WIDTH_TO_CODEWORD table lookup.
pub fn compute_ext_codewords_from_widths(
    normalized_widths: &[Vec<[u32; 6]>],
    words_with_dummies: &[Vec<u64>],
) -> Vec<Vec<u32>> {
    normalized_widths
        .iter()
        .zip(words_with_dummies.iter())
        .map(|(row_widths, row_words)| {
            row_widths
                .iter()
                .zip(row_words.iter())
                .map(|(_, &word)| ext_codeword_of_width(word))
                .collect()
        })
        .collect()
}

/// [u32; 6] variant of compute_garbage_word_witnesses. Uses base-13 width-word encoding.
pub fn compute_garbage_word_witnesses(
    normalized_widths: &[Vec<[u32; 6]>],
) -> (Vec<u64>, Vec<u64>) {
    normalized_widths
        .iter()
        .map(|row| {
            row.iter()
                .enumerate()
                .find(|(_, widths)| {
                    let word = get_word(widths);
                    word != START_WORD && word != STOP_WORD && !decodes_exactly(widths)
                })
                .map(|(idx, widths)| (get_word(widths), idx as u64))
                .unwrap_or_else(|| {
                    panic!("garbage row has no invalid word — row widths: {:?}", row)
                })
        })
        .unzip()
}

/// For each row in `image`, splits it into chunks of 10 pixels and computes:
/// - `int_val`: the chunk as a binary integer (bit i = pixel i)
/// - `blocks_base_b`: the run-length block vector encoded in base B (big-endian)
/// - `r`: length of the last block
/// - `nb`: number of blocks
/// - `odd`: nb % 2
/// - `block`: 1 if the last block is black, 0 if white
fn compute_lookups_and_raw_decomps<const N: usize>(
    image: &BitMatrix,
    B: usize,
    L: usize,
) -> (Vec<Vec<BlockLookup>>, Vec<Vec<[u16; N]>>) {
    let width = image.width() as usize;
    let height = image.height() as usize;
    let mut lookups: Vec<Vec<BlockLookup>> = Vec::new();
    let mut decomps: Vec<Vec<[u16; N]>> = Vec::new();

    for row in 0..height {
        let num_chunks = width.div_ceil(L);
        let mut row_lookups = Vec::new();
        let mut row_decomps = Vec::new();
        for chunk in 0..num_chunks {
            let mut decomp: [u16; N] = [0; N];
            let start_col = chunk * L;

            // Take chunk_len pixels and compute int as a binary string (big endian)
            let mut int_val: u16 = 0;
            let mut pixels: Vec<bool> = Vec::with_capacity(L);
            for i in 0..L {
                let px = image.get((start_col + i) as u32, row as u32);
                pixels.push(px);
                if px {
                    int_val |= 1 << i;
                }
            }

            // Compute blocks: lengths of runs of the same color
            let mut blocks_vec: Vec<u16> = Vec::new();
            let mut current_run: u16 = 1;
            for i in 1..L {
                if pixels[i] == pixels[i - 1] {
                    current_run += 1;
                } else {
                    blocks_vec.push(current_run);
                    current_run = 1;
                }
            }
            blocks_vec.push(current_run);

            let nb_usize = blocks_vec.len();

            // Big-endian base-B encoding and decomposition
            let mut blocks_base_b: u128 = 0;
            let num_non_remainder = nb_usize - 1;
            for (i, &b) in blocks_vec[..num_non_remainder].iter().enumerate() {
                blocks_base_b += b as u128 * (B as u128).pow(i as u32);
                decomp[i] = b;
            }

            let next_power_of_B = (B as u128).pow(num_non_remainder as u32);

            row_decomps.push(decomp); // this decomp ignores the remainder blocks

            let nb = num_non_remainder as u8;
            let odd: u8 = nb % 2;
            let first_is_black = pixels[0];

            // remainder = rightmost block length (remainder that may merge with the next chunk)
            let remainder = *blocks_vec.last().unwrap();

            // remainder_is_black = 1 if the rightmost block is black, 0 if white.
            // Uses actual block count (nb_usize) to determine the color of the last run.
            let last_is_black = if (nb_usize - 1) % 2 == 0 {
                first_is_black
            } else {
                !first_is_black
            };
            let remainder_is_black: u8 = if last_is_black { 1 } else { 0 };

            row_lookups.push(BlockLookup {
                binary_enc: int_val,
                baseB_enc: blocks_base_b,
                remainder,
                num_blocks: num_non_remainder as u8,
                num_blocks_is_odd: odd,
                remainder_is_black,
                next_power_of_B,
            });
        }
        lookups.push(row_lookups);
        decomps.push(row_decomps);
    }

    (lookups, decomps)
}

// Iterate through the chunks and combine remainders with the next block such that there are no breaks in the middle of blocks
// Return the base-B decomposition of these new, combined chunks
// N is max number of blocks per chunk
fn accumulate_decomps<const N: usize>(
    lookups: &mut Vec<Vec<BlockLookup>>,
    decomps: Vec<Vec<[u16; N]>>,
    B: usize,
) -> Vec<Vec<[u16; N]>> {
    lookups
        .iter_mut()
        .zip(decomps)
        .map(|(row_lookups, row_raw)| {
            let mut result = Vec::new();
            let mut decomp = row_raw[0];
            let mut last_remainder = row_lookups[0].remainder;
            let mut last_remainder_is_black = row_lookups[0].remainder_is_black != 0;

            for (lookup, next_decomp) in row_lookups[1..].iter().zip(row_raw[1..].iter().copied()) {
                result.push(decomp);
                decomp = next_decomp;

                if lookup.num_blocks == 0 {
                    let remainder_is_black = lookup.remainder_is_black != 0;
                    if last_remainder_is_black == remainder_is_black {
                        // same color: chunk merges into running remainder, block_chunks[i]=0 → zero decomp
                        last_remainder += lookup.remainder;
                        decomp = [0; N];
                    } else {
                        // different colors: commit previous remainder as last block
                        decomp.copy_within(0..N - 1, 1);
                        decomp[0] = last_remainder;
                        last_remainder = lookup.remainder;
                        last_remainder_is_black = remainder_is_black;
                    }
                } else {
                    // offset = XOR(remainder_is_black, black_r, num_blocks_is_odd)
                    //        = 0 if even parity among the three bits, 1 if odd parity
                    let offset: bool = (lookup.remainder_is_black != 0)
                        ^ last_remainder_is_black
                        ^ (lookup.num_blocks_is_odd != 0);

                    if offset {
                        decomp.copy_within(0..N - 1, 1); // scoot all the decomps over 1 to make room
                        decomp[0] = last_remainder; // put the remainder in the first position
                    } else {
                        decomp[0] += last_remainder;
                    }
                    last_remainder = lookup.remainder;
                    last_remainder_is_black = lookup.remainder_is_black != 0;
                }
            }

            // The final remainder goes at the first zero slot; update next_power_of_B accordingly.
            let final_pos = decomp.iter().position(|&x| x == 0).unwrap_or(N);
            row_lookups.last_mut().unwrap().next_power_of_B = (B as u128).pow(final_pos as u32);

            decomp[final_pos] = last_remainder;
            result.push(decomp);
            result
        })
        .collect()
}

pub fn compute_lookups_and_decomps<const N: usize>(
    image: &BitMatrix,
    B: usize,
    L: usize,
) -> (Vec<Vec<BlockLookup>>, Vec<Vec<[u16; N]>>) {
    let (mut lookups, raw_decomps) = compute_lookups_and_raw_decomps::<N>(image, B, L);
    let finalized_decomps = accumulate_decomps::<N>(&mut lookups, raw_decomps, B);
    (lookups, finalized_decomps)
}

/// For each row in `image`, computes the run-length block vector (lengths of
/// consecutive same-color pixel runs), zero-padded to `len`.
pub fn compute_blocks(image: &BitMatrix, len: usize) -> Vec<Vec<u32>> {
    let width = image.width() as usize;
    let height = image.height() as usize;
    let mut result: Vec<Vec<u32>> = Vec::new();

    for r in 0..height {
        let mut row_result = Vec::new();
        if width == 0 {
            continue;
        }
        let mut current_run: u32 = 1;
        for i in 1..width {
            let prev = image.get((i - 1) as u32, r as u32);
            let curr = image.get(i as u32, r as u32);
            if curr == prev {
                current_run += 1;
            } else {
                row_result.push(current_run);
                current_run = 1;
            }
        }
        row_result.push(current_run);
        row_result.resize(len, 0);
        result.push(row_result);
    }

    result
}

pub const DUMMY_CW: u32 = 919;

pub fn compute_normalized_widths(blocks: &[Vec<u32>]) -> Vec<Vec<[u32; 6]>> {
    blocks
        .iter()
        .map(|row| {
            row.chunks_exact(8)
                .map(|window| {
                    if window.iter().any(|&x| x == 0) {
                        [0u32; 6]
                    } else {
                        let sum: u32 = window.iter().sum();
                        let mut widths = [0; 6];
                        for i in 1..7 {
                            let raw_width = window[i] + window[i - 1];
                            widths[i - 1] = (raw_width as f32 * 17.0 / sum as f32).round() as u32;
                        }
                        widths
                    }
                })
                .collect()
        })
        .collect()
}


#[cfg(test)]
mod tests {
    use super::*;
    use crate::common::BitMatrix;

    fn make_bitmatrix(rows: &[&[bool]]) -> BitMatrix {
        let height = rows.len();
        let width = rows.first().map_or(0, |r| r.len());
        let mut bm = BitMatrix::new(width as u32, height as u32).unwrap();
        for (y, row) in rows.iter().enumerate() {
            for (x, &px) in row.iter().enumerate() {
                if px {
                    bm.set(x as u32, y as u32);
                }
            }
        }
        bm
    }

    // -------------------------------------------------------------------------
    // compute_lookups_and_decomps
    // -------------------------------------------------------------------------

    #[test]
    fn test_compute_lookups_all_white() {
        // Single row, 5 white pixels → one block of length 5
        let image = make_bitmatrix(&[&[false, false, false, false, false]]);
        let (lookups, decomps) = compute_lookups_and_decomps::<2>(&image, 104, 5);

        assert_eq!(lookups.len(), 1);
        assert_eq!(decomps.len(), 1);
        let l = &lookups[0][0];
        assert_eq!(l.binary_enc, 0);
        assert_eq!(l.baseB_enc, 0); // single block: no non-remainder blocks to encode
        assert_eq!(l.remainder, 5);
        assert_eq!(l.num_blocks, 0); // num_blocks does not include the remainder
        assert_eq!(l.num_blocks_is_odd, 0); // 0 % 2 == 1
        assert_eq!(l.remainder_is_black, 0); // rightmost block is white
        assert_eq!(decomps[0][0], [5u16, 0u16]); // enc_baseB=5 → only one block of len 5
    }

    #[test]
    fn test_compute_lookups_all_black() {
        // Single row, 5 black pixels → one block of length 5
        let image = make_bitmatrix(&[&[true, true, true, true, true]]);
        let (lookups, decomps) = compute_lookups_and_decomps::<2>(&image, 104, 5);

        assert_eq!(lookups.len(), 1);
        let l = &lookups[0][0];
        assert_eq!(l.binary_enc, 0b11111); // all 5 bits set
        assert_eq!(l.baseB_enc, 0); // single block: no non-remainder blocks to encode
        assert_eq!(l.remainder, 5);
        assert_eq!(l.num_blocks, 0);
        assert_eq!(l.num_blocks_is_odd, 0); // 0 % 2 == 0
        assert_eq!(l.remainder_is_black, 1); // rightmost block is black
        assert_eq!(decomps[0][0], [5u16, 0u16]); // enc_baseB=5 → only one block of len 5
    }

    #[test]
    fn test_compute_lookups_two_blocks() {
        // 3 black then 7 white, fills exactly one chunk of 10
        let row: &[bool] = &[
            true, true, true, false, false, false, false, false, false, false,
        ];
        let image = make_bitmatrix(&[row]);
        let (lookups, decomps) = compute_lookups_and_decomps::<2>(&image, 104, 10);

        assert_eq!(lookups.len(), 1);
        let l = &lookups[0][0];
        assert_eq!(l.binary_enc, 0b0000000111); // first three bits set (big endian encoding)
        // leftmost block (3) is the only non-remainder block: enc_baseB = 3 * B^0 = 3
        assert_eq!(l.baseB_enc, 3);
        assert_eq!(l.remainder, 7);
        assert_eq!(l.num_blocks, 1);
        assert_eq!(l.num_blocks_is_odd, 1); // 1 % 2 == 1
        // first_is_black=true, (2-1)%2=1 → last is opposite → white → remainder_is_black=0
        assert_eq!(l.remainder_is_black, 0);
        assert_eq!(l.next_power_of_B, 104); // single chunk, final_pos=1 → B^1=104
        assert_eq!(decomps[0][0], [3u16, 7u16]);
    }

    #[test]
    fn test_compute_lookups_four_blocks() {
        // [W,B,B,W,W,W,W,B,B,B] → blocks [1,2,4,3], N=4
        let row: &[bool] = &[
            false, true, true, false, false, false, false, true, true, true,
        ];
        let image = make_bitmatrix(&[row]);
        let (lookups, decomps) = compute_lookups_and_decomps::<4>(&image, 1080, 10);

        let l = &lookups[0][0];
        assert_eq!(l.num_blocks, 3);
        assert_eq!(l.num_blocks_is_odd, 1);
        assert_eq!(l.remainder, 3);
        // first_is_black=false, (nb-1)%2=3%2=1 → last is opposite → black → remainder_is_black=1
        assert_eq!(l.remainder_is_black, 1);
        // decomp is little-endian of non-remainder blocks [1,2,4]:
        //   decomp[0]=4 (coeff of B^0), decomp[1]=2 (B^1), decomp[2]=1 (B^2), decomp[3]=0 (pad)
        assert_eq!(decomps[0][0], [1u16, 2u16, 4u16, 3u16]);
        // baseB_enc = 4*1080^2 + 2*1080 + 1 (excludes remainder=3)
        let expected = 4u128 * 1080u128.pow(2) + 2 * 1080 + 1;
        assert_eq!(l.baseB_enc, expected);
        assert_eq!(l.next_power_of_B, 1080u128.pow(3)); // single chunk, final_pos=3 → B^3
    }

    #[test]
    fn test_compute_lookups_multiple_chunks() {
        // Width=20, one row: first 2 cols black, cols 15-19 black
        // Chunk 0 (cols 0-9):  [T,T,F,F,F,F,F,F,F,F] → blocks [2,8]
        // Chunk 1 (cols 10-19):[F,F,F,F,F,T,T,T,T,T] → blocks [5,5]
        let mut row = vec![false; 20];
        row[0] = true;
        row[1] = true;
        for i in 15..20 {
            row[i] = true;
        }
        let image = make_bitmatrix(&[row.as_slice()]);
        let (lookups, decomps) = compute_lookups_and_decomps::<2>(&image, 104, 10);

        assert_eq!(lookups.len(), 1); // 1 row
        assert_eq!(lookups[0].len(), 2); // 2 chunks
        assert_eq!(decomps[0].len(), 2);

        // Chunk 0
        let l0 = &lookups[0][0];
        assert_eq!(l0.binary_enc, 0b0000000011); // 2 LSB's are true
        assert_eq!(l0.baseB_enc, 2); // excludes remainder
        assert_eq!(l0.remainder, 8);
        assert_eq!(l0.num_blocks, 1);
        assert_eq!(l0.num_blocks_is_odd, 1);
        assert_eq!(l0.remainder_is_black, 0); // first=black, (nb-1)%2=1 → last=white
        assert_eq!(decomps[0][0], [2u16, 0u16]);

        // Chunk 1
        let l1 = &lookups[0][1];
        // pixels 5-9 of the chunk (cols 15-19) are black → bits 5-9 set
        assert_eq!(l1.binary_enc, 0b1111100000);
        assert_eq!(l1.baseB_enc, 5); // excluding remainder
        assert_eq!(l1.remainder, 5);
        assert_eq!(l1.num_blocks, 1);
        assert_eq!(l1.num_blocks_is_odd, 1);
        assert_eq!(l1.remainder_is_black, 1); // first=white, (nb-1)%2=1 → last=black
        assert_eq!(l1.next_power_of_B, 104); // offset=0 (merge), final_pos=1 → B^1=104
        assert_eq!(decomps[0][1], [13u16, 5u16]);
    }

    #[test]
    fn test_compute_lookups_multiple_rows() {
        // 2 rows: all-black, all-white
        let image = make_bitmatrix(&[
            &[true, true, true, true, true],
            &[false, false, false, false, false],
        ]);
        let (lookups, decomps) = compute_lookups_and_decomps::<2>(&image, 104, 5);

        assert_eq!(lookups.len(), 2); // 2 rows
        assert_eq!(lookups[0].len(), 1); // 1 chunk per row
        assert_eq!(lookups[1].len(), 1);
        assert_eq!(decomps.len(), 2);
        assert_eq!(lookups[0][0].remainder_is_black, 1); // row 0: last block black
        assert_eq!(lookups[1][0].remainder_is_black, 0); // row 1: last block white
        assert_eq!(lookups[0][0].next_power_of_B, 1); // single chunk, final_pos=0 → B^0=1
        assert_eq!(lookups[1][0].next_power_of_B, 1); // single chunk, final_pos=0 → B^0=1
        assert_eq!(decomps[0][0], [5u16, 0u16]);
        assert_eq!(decomps[1][0], [5u16, 0u16]);
    }

    #[test]
    fn test_compute_lookups_zero_block() {
        let row: &[bool] = &[
            false, false, false, false, false, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true, true, true, true, true, false, false, false, false,
            false, false, false,
        ];
        let image = make_bitmatrix(&[row]);
        let (lookups, decomps) = compute_lookups_and_decomps::<2>(&image, 104, 10);
        assert_eq!(lookups.len(), 1); // 1 row
        assert_eq!(lookups[0].len(), 3); // 3 chunks in row
        assert_eq!(decomps.len(), 1);
        assert_eq!(decomps[0].len(), 3); // 3 block chunks
        assert_eq!(decomps[0][0], [5u16, 0u16]);
        assert_eq!(decomps[0][1], [0u16, 0u16]); // 0 decomp for 0 block chunk
        assert_eq!(decomps[0][2], [18u16, 7u16]); // combined chunk and last remainder
        assert_eq!(lookups[0][2].next_power_of_B, 104); // offset=0 (merge), final_pos=1 → B^1=104
    }

    #[test]
    fn test_compute_lookups_zero_block_no_merge() {
        let row: &[bool] = &[
            false, false, false, false, false, true, true, true, true, true, false, false, false,
            false, false, false, false, false, false, false, true, true, false, false, false,
            false, false, false, false, false,
        ];
        let image = make_bitmatrix(&[row]);
        let (lookups, decomps) = compute_lookups_and_decomps::<3>(&image, 104, 10);
        assert_eq!(lookups.len(), 1); // 1 row
        assert_eq!(lookups[0].len(), 3); // 5 chunks in row
        assert_eq!(decomps.len(), 1);
        assert_eq!(decomps[0].len(), 3); // 4 block chunks
        assert_eq!(decomps[0][0], [5u16, 0, 0]);
        assert_eq!(decomps[0][1], [5u16, 0, 0]); // nb = 0 but previous remainder goes here
        assert_eq!(decomps[0][2], [10u16, 2, 8]);
        assert_eq!(lookups[0][2].next_power_of_B, 10816); // offset=1 (separate), final_pos=2 → B^2=10816
    }

    #[test]
    fn test_compute_lookups_even_nb_black_remainder() {
        // Tests the case: odd=0, remainder_is_black=1 (previously buggy path in first_block_is_black).
        //
        // Row (20px, 2 chunks):
        //   Chunk 0: [T,T,T,T,T,F,F,F,F,F] → blocks [5,5], nb=1, odd=1, rem=5 (white)
        //   Chunk 1: [T,T,T,F,F,T,T,T,T,T] → blocks [3,2,5], nb=2, odd=0, rem=5 (black)
        //
        // Chunk 1's first block is black (= rem_is_black XOR odd = 1 XOR 0 = black).
        // Prev remainder (chunk 0) is white → different colors → no merge.
        // Decomp[1] should be [prev_rem=5, block0=3, block1=2, final_rem=5] = [5,3,2,5].
        //
        // With the old buggy formula (odd && !rb = false), the code thought first was white
        // and merged at the wrong index, producing [0, 8, 2, 5] instead.
        let row: &[bool] = &[
            true, true, true, true, true, false, false, false, false, false, // chunk 0
            true, true, true, false, false, true, true, true, true, true, // chunk 1
        ];
        let image = make_bitmatrix(&[row]);
        let (lookups, decomps) = compute_lookups_and_decomps::<4>(&image, 104, 10);

        assert_eq!(lookups[0].len(), 2);

        // Chunk 0: nb=1, odd=1, remainder_is_black=0
        let l0 = &lookups[0][0];
        assert_eq!(l0.num_blocks, 1);
        assert_eq!(l0.num_blocks_is_odd, 1);
        assert_eq!(l0.remainder, 5);
        assert_eq!(l0.remainder_is_black, 0);

        // Chunk 1: nb=2, odd=0, remainder_is_black=1 — the key case
        let l1 = &lookups[0][1];
        assert_eq!(l1.num_blocks, 2);
        assert_eq!(l1.num_blocks_is_odd, 0);
        assert_eq!(l1.remainder, 5);
        assert_eq!(l1.remainder_is_black, 1);

        // Chunk 0 decomp: only its one non-remainder block (5); its remainder feeds into chunk 1
        assert_eq!(decomps[0][0], [5u16, 0, 0, 0]);
        // Chunk 1 decomp: [prev_rem=5, block0=3, block1=2, final_rem=5]
        // baseB_sum = 5*104^3 + 3*104^2 + 2*104 + 5 = 5656981 = block_chunks[1] in circuit
        assert_eq!(decomps[0][1], [5u16, 3, 2, 5]);
        assert_eq!(lookups[0][1].next_power_of_B, 1124864); // offset=1 (separate), final_pos=3 → B^3=104^3=1124864
    }

    // -------------------------------------------------------------------------
    // compute_blocks
    // -------------------------------------------------------------------------

    #[test]
    fn test_compute_blocks_basic() {
        // [T,T,F,F,F] → run-lengths [2, 3], padded to len=5
        let image = make_bitmatrix(&[&[true, true, false, false, false]]);
        let blocks = compute_blocks(&image, 5);
        assert_eq!(blocks.len(), 1);
        assert_eq!(blocks[0][0], 2);
        assert_eq!(blocks[0][1], 3);
        assert_eq!(blocks[0][2], 0); // zero-padded
    }

    #[test]
    fn test_compute_blocks_single_run() {
        // All white → one run, padded to len=4
        let image = make_bitmatrix(&[&[false, false, false, false]]);
        let blocks = compute_blocks(&image, 4);
        assert_eq!(blocks[0][0], 4);
        for &b in &blocks[0][1..] {
            assert_eq!(b, 0);
        }
    }

    #[test]
    fn test_compute_blocks_multiple_rows() {
        let image = make_bitmatrix(&[
            &[true, true, false],   // [2, 1]
            &[false, false, false], // [3]
        ]);
        let blocks = compute_blocks(&image, 4);
        assert_eq!(blocks.len(), 2);
        assert_eq!(blocks[0][0], 2);
        assert_eq!(blocks[0][1], 1);
        assert_eq!(blocks[1][0], 3);
        assert_eq!(blocks[1][1], 0);
    }

    const START_BLOCKS: [u32; 8] = [8, 1, 1, 1, 1, 1, 1, 3];
    const STOP_BLOCKS: [u32; 8] = [7, 1, 1, 3, 1, 1, 1, 2];

    // -------------------------------------------------------------------------
    // compute_normalized_widths
    // -------------------------------------------------------------------------

    #[test]
    fn test_normalized_widths_basic() {
        // [1,2,3,4,5,6,7,8] → round(17*(b[i]+b[i+1])/36) for i in 0..6
        let blocks = vec![vec![1u32, 2, 3, 4, 5, 6, 7, 8]];
        let widths = compute_normalized_widths(&blocks);
        assert_eq!(widths.len(), 1);
        assert_eq!(widths[0].len(), 1);
        assert_eq!(widths[0][0], [1, 2, 3, 4, 5, 6]);
    }

    #[test]
    fn test_normalized_widths_zero_element_gives_all_zero() {
        // Any zero in the window → all-zero output, same as compute_normalized_blocks.
        let blocks = vec![vec![1u32, 2, 0, 4, 5, 6, 7, 8]];
        let widths = compute_normalized_widths(&blocks);
        assert_eq!(widths[0][0], [0u32; 6]);
    }

    #[test]
    fn test_normalized_widths_last_element_affects_sum() {
        // Element 7 does not appear in any pair numerator, but it does affect the
        // window sum (denominator), so changing it changes the output widths.
        let blocks_a = vec![vec![1u32, 2, 3, 4, 5, 6, 7, 8]];  // sum=36
        let blocks_b = vec![vec![1u32, 2, 3, 4, 5, 6, 7, 99]]; // sum=127
        assert_ne!(
            compute_normalized_widths(&blocks_a),
            compute_normalized_widths(&blocks_b)
        );
    }

    #[test]
    fn test_normalized_widths_multiple_chunks() {
        // 16 elements → 2 chunks, each normalized independently.
        let blocks = vec![vec![
            1u32, 1, 1, 1, 1, 1, 1, 1, // chunk 0: all 1s, sum=8 → each pair=2, round(17*2/8)=4
            2, 3, 4, 5, 6, 7, 8, 9, // chunk 1: ascending, sum=44
        ]];
        let widths = compute_normalized_widths(&blocks);
        assert_eq!(widths[0].len(), 2);
        assert_eq!(widths[0][0], [4, 4, 4, 4, 4, 4]);
        assert_eq!(widths[0][1], [2, 3, 3, 4, 5, 6]);
    }

    #[test]
    fn test_normalized_widths_partial_chunk_ignored() {
        // chunks_exact(8) discards elements that don't fill a full window.
        let blocks = vec![vec![1u32, 2, 3, 4, 5, 6, 7, 8, 9]]; // 9 → 1 window + 1 leftover
        let widths = compute_normalized_widths(&blocks);
        assert_eq!(widths[0].len(), 1);
    }

    #[test]
    fn test_normalized_widths_multiple_rows() {
        // Each row is processed independently.
        let blocks = vec![
            vec![1u32, 2, 3, 4, 5, 6, 7, 8],
            vec![0u32, 1, 2, 3, 4, 5, 6, 7], // first element is zero
            vec![],
        ];
        let widths = compute_normalized_widths(&blocks);
        assert_eq!(widths.len(), 3);
        assert_eq!(widths[0][0], [1, 2, 3, 4, 5, 6]);
        assert_eq!(widths[1][0], [0u32; 6]); // zero-filtered
        assert_eq!(widths[2].len(), 0); // empty row → no chunks
    }

    #[test]
    fn test_normalized_widths_start_pattern() {
        // START_BLOCKS = [8,1,1,1,1,1,1,3], sum=17 → round(17*pair/17) = pair exactly
        let blocks = vec![Vec::from(START_BLOCKS)];
        let widths = compute_normalized_widths(&blocks);
        assert_eq!(widths[0][0], [9, 2, 2, 2, 2, 2]); // 8+1, 1+1, 1+1, 1+1, 1+1, 1+1
    }

    #[test]
    fn test_normalized_widths_stop_pattern() {
        // STOP_BLOCKS = [7,1,1,3,1,1,1,2], sum=17 → round(17*pair/17) = pair exactly
        let blocks = vec![Vec::from(STOP_BLOCKS)];
        let widths = compute_normalized_widths(&blocks);
        assert_eq!(widths[0][0], [8, 2, 4, 4, 2, 2]); // 7+1, 1+1, 1+3, 3+1, 1+1, 1+1
    }

    // -------------------------------------------------------------------------
    // get_word / width-word constants
    // -------------------------------------------------------------------------

    #[test]
    fn test_get_word_start_pattern() {
        // Start pattern [8,1,1,1,1,1,3] → widths [9,2,2,2,2,2] → base-13 little-endian
        let widths: [u32; 6] = [9, 2, 2, 2, 2, 2];
        assert_eq!(get_word(&widths), START_WORD);
    }

    #[test]
    fn test_get_word_stop_pattern() {
        // Stop pattern [7,1,1,3,1,1,1,2] → widths [8,2,4,4,2,2]
        let widths: [u32; 6] = [8, 2, 4, 4, 2, 2];
        assert_eq!(get_word(&widths), STOP_WORD);
    }

    #[test]
    fn test_get_word_max_width_no_collision() {
        // Width value of 12 (6+6) must encode safely in base-13.
        // Two patterns differing only in whether one slot is 12 or (6,6 split) must differ.
        let a: [u32; 6] = [12, 1, 1, 1, 1, 1];
        let b: [u32; 6] = [1, 12, 1, 1, 1, 1];
        assert_ne!(get_word(&a), get_word(&b));
        // Also check a 12 doesn't alias a two-digit base-10 sequence
        let c: [u32; 6] = [2, 1, 1, 1, 1, 1]; // would collide with [12,...] in base-10
        assert_ne!(get_word(&a), get_word(&c));
    }

    // -------------------------------------------------------------------------
    // decodes_exactly / ext_codeword_of_width
    // -------------------------------------------------------------------------

    #[test]
    fn test_decodes_exactly_valid_codeword() {
        // First pattern in PATTERNS: 31111136 → widths [4,2,2,2,2,2]
        // 3+1=4, 1+1=2, 1+1=2, 1+1=2, 1+1=2, 1+3=4 — wait, digit 7 (=6) excluded:
        // digits [3,1,1,1,1,1,3,6], widths[0..6] = [4,2,2,2,2,4]
        let widths: [u32; 6] = [4, 2, 2, 2, 2, 4];
        assert!(decodes_exactly(&widths));
    }

    #[test]
    fn test_decodes_exactly_all_zero() {
        assert!(!decodes_exactly(&[0u32; 6]));
    }

    #[test]
    fn test_decodes_exactly_invalid_pattern() {
        // [1,1,1,1,1,1] is not a valid PDF417 width pattern
        assert!(!decodes_exactly(&[1u32; 6]));
    }

    #[test]
    fn test_ext_codeword_of_width_start() {
        assert_eq!(ext_codeword_of_width(START_WORD), DUMMY_CW);
    }

    #[test]
    fn test_ext_codeword_of_width_stop() {
        assert_eq!(ext_codeword_of_width(STOP_WORD), DUMMY_CW);
    }

    #[test]
    fn test_ext_codeword_of_width_zero() {
        assert_eq!(ext_codeword_of_width(0), DUMMY_CW);
    }

    #[test]
    fn test_ext_codeword_of_width_first_codeword() {
        // Pattern 31111136 is codeword index 0. widths = [4,2,2,2,2,4].
        let widths: [u32; 6] = [4, 2, 2, 2, 2, 4];
        let word = get_word(&widths);
        assert_eq!(ext_codeword_of_width(word), 0u32);
    }

    // -------------------------------------------------------------------------
    // compute_garbage_word_witnesses
    // -------------------------------------------------------------------------

    #[test]
    fn test_garbage_witnesses_zero_row_picks_col_0() {
        // All-zero widths: get_word returns 0 (not a valid word) → pick column 0.
        let row = vec![[0u32; 6]; 4];
        let (words, indices) = compute_garbage_word_witnesses(&[row]);
        assert_eq!(words, vec![0u64]);
        assert_eq!(indices, vec![0u64]);
    }

    #[test]
    fn test_garbage_witnesses_skips_start() {
        // Column 0 is START widths; column 1 is all-zero (invalid).
        let start_widths: [u32; 6] = [9, 2, 2, 2, 2, 2];
        let row = vec![start_widths, [0u32; 6]];
        let (words, indices) = compute_garbage_word_witnesses(&[row]);
        assert_eq!(words[0], 0u64);
        assert_eq!(indices[0], 1u64);
    }

    #[test]
    fn test_garbage_witnesses_skips_stop() {
        let stop_widths: [u32; 6] = [8, 2, 4, 4, 2, 2];
        let row = vec![stop_widths, [0u32; 6]];
        let (words, indices) = compute_garbage_word_witnesses(&[row]);
        assert_eq!(words[0], 0u64);
        assert_eq!(indices[0], 1u64);
    }

    #[test]
    fn test_garbage_witnesses_picks_first_invalid_not_last() {
        // Column 0 is zero (invalid); column 1 is START (excluded); column 2 is zero.
        let start_widths: [u32; 6] = [9, 2, 2, 2, 2, 2];
        let row = vec![[0u32; 6], start_widths, [0u32; 6]];
        let (words, indices) = compute_garbage_word_witnesses(&[row]);
        assert_eq!(words[0], 0u64);
        assert_eq!(indices[0], 0u64);
    }

    #[test]
    fn test_garbage_witnesses_multiple_rows_independent() {
        let start_widths: [u32; 6] = [9, 2, 2, 2, 2, 2];
        let rows = vec![
            vec![start_widths, [0u32; 6]], // row 0: skips START, picks col 1
            vec![[0u32; 6]; 3],            // row 1: all zero, picks col 0
        ];
        let (words, indices) = compute_garbage_word_witnesses(&rows);
        assert_eq!(words, vec![0u64, 0u64]);
        assert_eq!(indices, vec![1u64, 0u64]);
    }

    #[test]
    fn test_garbage_witnesses_word_value_is_correct() {
        // Use a non-zero invalid width pattern and verify the returned word value.
        let invalid_widths: [u32; 6] = [3, 3, 3, 3, 3, 2]; // sum-of-pairs not matching any codeword
        let expected_word = get_word(&invalid_widths);
        let start_widths: [u32; 6] = [9, 2, 2, 2, 2, 2];
        let row = vec![start_widths, invalid_widths];
        let (words, indices) = compute_garbage_word_witnesses(&[row]);
        assert_eq!(words[0], expected_word);
        assert_eq!(indices[0], 1u64);
    }

    #[test]
    #[should_panic(expected = "garbage row has no invalid word")]
    fn test_garbage_witnesses_panics_when_no_invalid_word() {
        let start_widths: [u32; 6] = [9, 2, 2, 2, 2, 2];
        let stop_widths: [u32; 6] = [8, 2, 4, 4, 2, 2];
        let row = vec![start_widths, stop_widths, start_widths];
        compute_garbage_word_witnesses(&[row]);
    }

    // -------------------------------------------------------------------------
    // compute_words_with_dummies
    // -------------------------------------------------------------------------

    #[test]
    fn test_words_with_dummies_duplicate_row_zeroed() {
        // Two identical rows of all-zero widths: second row should be zeroed as duplicate.
        let row = vec![[0u32; 6]; 3];
        let (wwd, _garbage) = compute_words_with_dummies(&[row.clone(), row]);
        // Row 0 is kept (all-zero words → treated as non-decodable, become 0 anyway)
        // Row 1 is a consecutive duplicate → all zeros
        assert!(wwd[1].iter().all(|&w| w == 0));
    }

    #[test]
    fn test_words_with_dummies_start_kept() {
        // START widths should be kept (not zeroed) in words_with_dummies.
        let start_widths: [u32; 6] = [9, 2, 2, 2, 2, 2];
        let zero = [0u32; 6];
        let row = vec![start_widths, zero, zero];
        let (wwd, _) = compute_words_with_dummies(&[row]);
        assert_eq!(wwd[0][0], START_WORD);
        assert_eq!(wwd[0][1], 0u64);
    }
}
